-- MySQL Script generated by MySQL Workbench
-- Thu May 18 19:08:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fluxsys_db_dev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fluxsys_db_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fluxsys_db_dev` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `fluxsys_db_dev` ;

-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`UnidadesProduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`UnidadesProduccion` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`Agentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`Agentes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Apellido` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Cargo` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Dni` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Firma` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Matricula` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  `UnidadProduccionAgenteId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Agentes_UnidadProduccionAgenteId` (`UnidadProduccionAgenteId` ASC) VISIBLE,
  CONSTRAINT `FK_Agentes_UnidadesProduccion_UnidadProduccionAgenteId`
    FOREIGN KEY (`UnidadProduccionAgenteId`)
    REFERENCES `fluxsys_db_dev`.`UnidadesProduccion` (`Id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`AspNetRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`AspNetRoles` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT,
  `Permisos` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  `Name` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `NormalizedName` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ConcurrencyStamp` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `RoleNameIndex` (`NormalizedName` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 152
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`AspNetRoleClaims`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`AspNetRoleClaims` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `RoleId` BIGINT NOT NULL,
  `ClaimType` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ClaimValue` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_AspNetRoleClaims_RoleId` (`RoleId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetRoleClaims_AspNetRoles_RoleId`
    FOREIGN KEY (`RoleId`)
    REFERENCES `fluxsys_db_dev`.`AspNetRoles` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`AspNetUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`AspNetUsers` (
  `Id` BIGINT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Apellido` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Conectado` TINYINT(1) NOT NULL,
  `IdConexion` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  `UserName` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `NormalizedUserName` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Email` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `NormalizedEmail` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `EmailConfirmed` TINYINT(1) NOT NULL,
  `PasswordHash` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `SecurityStamp` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ConcurrencyStamp` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `PhoneNumber` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `PhoneNumberConfirmed` TINYINT(1) NOT NULL,
  `TwoFactorEnabled` TINYINT(1) NOT NULL,
  `LockoutEnd` DATETIME(6) NULL DEFAULT NULL,
  `LockoutEnabled` TINYINT(1) NOT NULL,
  `AccessFailedCount` INT NOT NULL,
  `IdentificadoresEquipoJuzgado` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `UserNameIndex` (`NormalizedUserName` ASC) VISIBLE,
  INDEX `EmailIndex` (`NormalizedEmail` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`AspNetUserClaims`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`AspNetUserClaims` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `UserId` BIGINT NOT NULL,
  `ClaimType` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ClaimValue` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_AspNetUserClaims_UserId` (`UserId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetUserClaims_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `fluxsys_db_dev`.`AspNetUsers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`AspNetUserLogins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`AspNetUserLogins` (
  `LoginProvider` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ProviderKey` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ProviderDisplayName` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `UserId` BIGINT NOT NULL,
  PRIMARY KEY (`LoginProvider`, `ProviderKey`),
  INDEX `IX_AspNetUserLogins_UserId` (`UserId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetUserLogins_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `fluxsys_db_dev`.`AspNetUsers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`AspNetUserRoles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`AspNetUserRoles` (
  `UserId` BIGINT NOT NULL,
  `RoleId` BIGINT NOT NULL,
  PRIMARY KEY (`UserId`, `RoleId`),
  INDEX `IX_AspNetUserRoles_RoleId` (`RoleId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetUserRoles_AspNetRoles_RoleId`
    FOREIGN KEY (`RoleId`)
    REFERENCES `fluxsys_db_dev`.`AspNetRoles` (`Id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_AspNetUserRoles_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `fluxsys_db_dev`.`AspNetUsers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`AspNetUserTokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`AspNetUserTokens` (
  `UserId` BIGINT NOT NULL,
  `LoginProvider` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `Value` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`UserId`, `LoginProvider`, `Name`),
  CONSTRAINT `FK_AspNetUserTokens_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `fluxsys_db_dev`.`AspNetUsers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`CodigosInfraccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`CodigosInfraccion` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Abreviatura` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Descripcion` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Codigo` INT NOT NULL,
  `Articulo` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Inciso` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ValorUfMax` FLOAT NOT NULL,
  `ValorUfMin` FLOAT NOT NULL,
  `Categoria` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Observaciones` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `PuntosRestados` INT NULL DEFAULT NULL,
  `Etiqueta` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  `SegmentosUf` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `EtiquetasImagenes` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `PermitirEtiquetaImagenDuplicada` TINYINT(1) NOT NULL DEFAULT '0',
  `Identificador` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`ConfiguracionesProduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`ConfiguracionesProduccion` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `UnidadProduccionId` INT NULL DEFAULT NULL,
  `TipoContenedorPrecarga` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `SftpHost` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `SftpPuerto` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `SftpUsuario` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `SftpContrasena` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `SftpRuta` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ContrasenaContenedor` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `EtiquetaCodigoInfracciones` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CodigoInfraccionId` INT NULL DEFAULT NULL,
  `ConfiguracionesFecha` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TipoExportacion` INT NOT NULL,
  `TipoImpresion` INT NOT NULL,
  `TemplateImpresion` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CodigoProveedorBA` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `AutoridadConstatacionBA` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CodigoJurisdiccionBA` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CodigoPostalBA` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `NombreProveedorBA` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `NumeroExportacionInicioBA` BIGINT NOT NULL,
  `NumeroDiaExportacionInicioBA` BIGINT NOT NULL,
  `NumeroInfraccionExportacionInicioBA` BIGINT NOT NULL,
  `PlataformaPago` INT NULL DEFAULT NULL,
  `BearerHelipagos` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ApiKeyHelipagos` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `IdOrganismoEpagos` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `IdUsuarioEpagos` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `HashEpagos` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `PasswordEpagos` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ConvenioEpagos` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  `LargoMinCodigoBarrasCorreo` INT NULL DEFAULT NULL,
  `PatronCodigoBarrasCorreo` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Email` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Horarios` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Ley` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Ordenanza` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Telefono` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `UrlApi` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `PrefijoTramite` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `BancoTransferencia` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `BannerMediosPago` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CbuTransferencia` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CuentaTransferencia` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CuitTransferencia` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Direccion` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Logo` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Subtitulo` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TextoAdvertenciaPagoVoluntario` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TextoCorreoRazonSocial` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TextoCorreoRetornar` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TextoHomologacion` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TextoInformacion` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TextoMaximo` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TextoMedido` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TextoObjeto` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Titulo` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `PrefijoSolicitudPago` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ConfiguracionesAdicionales` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TokenApiNroExportacion` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `UrlApiNroExportacion` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `VariableClienteApiNroExportacion` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `MetodoApiNroExportacion` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Municipio` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_ConfiguracionesProduccion_CodigoInfraccionId` (`CodigoInfraccionId` ASC) VISIBLE,
  INDEX `IX_ConfiguracionesProduccion_UnidadProduccionId` (`UnidadProduccionId` ASC) VISIBLE,
  CONSTRAINT `FK_ConfiguracionesProduccion_CodigosInfraccion_CodigoInfraccion~`
    FOREIGN KEY (`CodigoInfraccionId`)
    REFERENCES `fluxsys_db_dev`.`CodigosInfraccion` (`Id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_ConfiguracionesProduccion_UnidadesProduccion_UnidadProduccio~`
    FOREIGN KEY (`UnidadProduccionId`)
    REFERENCES `fluxsys_db_dev`.`UnidadesProduccion` (`Id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`Equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`Equipos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Modelo` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Nombre` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Descripcion` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ConfiguracionProduccionId` INT NULL DEFAULT NULL,
  `Categoria` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Tipo` INT NULL DEFAULT NULL,
  `NroSerie` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `AgenteId` INT NULL DEFAULT NULL,
  `FechaVencimientoVerificacion` DATETIME(6) NULL DEFAULT NULL,
  `FechaVerificacion` DATETIME(6) NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  `CodigoDnci` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CodigoPrimitiva` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Lugar` VARCHAR(300) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `UriTransmision` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `RegexFechaHoraNombreVideo` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Equipos_AgenteId` (`AgenteId` ASC) VISIBLE,
  INDEX `IX_Equipos_ConfiguracionProduccionId` (`ConfiguracionProduccionId` ASC) VISIBLE,
  CONSTRAINT `FK_Equipos_Agentes_AgenteId`
    FOREIGN KEY (`AgenteId`)
    REFERENCES `fluxsys_db_dev`.`Agentes` (`Id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_Equipos_ConfiguracionesProduccion_ConfiguracionProduccionId`
    FOREIGN KEY (`ConfiguracionProduccionId`)
    REFERENCES `fluxsys_db_dev`.`ConfiguracionesProduccion` (`Id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`ImagenesConfiguracionAnalitica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`ImagenesConfiguracionAnalitica` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  `BaseUrl` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `PathUrl` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Name` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Extension` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `SizeBytes` BIGINT NOT NULL,
  `FullUrl` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`ConfiguracionesAnalitica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`ConfiguracionesAnalitica` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Tipo` INT NOT NULL,
  `Areas` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `FormatoFechaHora` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `EquipoId` INT NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  `ClasesPermitidas` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ImagenId` INT NULL DEFAULT NULL,
  `CriterioSemaforo` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `DireccionCirculacion` INT NOT NULL DEFAULT '0',
  `Etiqueta` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_ConfiguracionesAnalitica_EquipoId` (`EquipoId` ASC) VISIBLE,
  INDEX `IX_ConfiguracionesAnalitica_ImagenId` (`ImagenId` ASC) VISIBLE,
  CONSTRAINT `FK_ConfiguracionesAnalitica_Equipos_EquipoId`
    FOREIGN KEY (`EquipoId`)
    REFERENCES `fluxsys_db_dev`.`Equipos` (`Id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_ConfiguracionesAnalitica_ImagenesConfiguracionAnalitica_Imag~`
    FOREIGN KEY (`ImagenId`)
    REFERENCES `fluxsys_db_dev`.`ImagenesConfiguracionAnalitica` (`Id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`Descargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`Descargos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  `Detalles` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Estado` INT NOT NULL DEFAULT '0',
  `FechaAceptado` DATETIME(6) NULL DEFAULT NULL,
  `FechaPresentado` DATETIME(6) NULL DEFAULT NULL,
  `FechaRechazado` DATETIME(6) NULL DEFAULT NULL,
  `Motivo` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`EquiposProcesamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`EquiposProcesamiento` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`Eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`Eventos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `UsuarioId` BIGINT NOT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Eventos_UsuarioId` (`UsuarioId` ASC) VISIBLE,
  CONSTRAINT `FK_Eventos_AspNetUsers_UsuarioId`
    FOREIGN KEY (`UsuarioId`)
    REFERENCES `fluxsys_db_dev`.`AspNetUsers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 77259
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`ExportacionesBA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`ExportacionesBA` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `CodigoNegocioInicio` BIGINT NOT NULL,
  `CodigoNegocioFin` BIGINT NOT NULL,
  `NroExportacionDiaInicio` BIGINT NOT NULL,
  `NroExportacionDiaFin` BIGINT NOT NULL,
  `NroExportacion` BIGINT NOT NULL,
  `FechaHora` DATETIME(6) NOT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  `BaseUrl` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `PathUrl` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Name` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Extension` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `SizeBytes` BIGINT NOT NULL,
  `FullUrl` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`LotesConsulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`LotesConsulta` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `FechaHora` DATETIME(6) NOT NULL,
  `Patentes` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CantidadPatentes` INT NOT NULL,
  `UltimoVerificadorId` BIGINT NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_LotesConsulta_UltimoVerificadorId` (`UltimoVerificadorId` ASC) VISIBLE,
  CONSTRAINT `FK_LotesConsulta_AspNetUsers_UltimoVerificadorId`
    FOREIGN KEY (`UltimoVerificadorId`)
    REFERENCES `fluxsys_db_dev`.`AspNetUsers` (`Id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 191
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`LotesExportacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`LotesExportacion` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `FechaHora` DATETIME(6) NOT NULL,
  `CantidadInfracciones` INT NOT NULL,
  `ExportacionBAId` INT NULL DEFAULT NULL,
  `TipoExportacion` INT NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_LotesExportacion_ExportacionBAId` (`ExportacionBAId` ASC) VISIBLE,
  CONSTRAINT `FK_LotesExportacion_ExportacionesBA_ExportacionBAId`
    FOREIGN KEY (`ExportacionBAId`)
    REFERENCES `fluxsys_db_dev`.`ExportacionesBA` (`Id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`LotesImpresion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`LotesImpresion` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `FechaHora` DATETIME(6) NOT NULL,
  `CantidadInfracciones` INT NOT NULL,
  `NroLote` INT NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  `AgenteFirmanteId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_LotesImpresion_AgenteFirmanteId` (`AgenteFirmanteId` ASC) VISIBLE,
  CONSTRAINT `FK_LotesImpresion_Agentes_AgenteFirmanteId`
    FOREIGN KEY (`AgenteFirmanteId`)
    REFERENCES `fluxsys_db_dev`.`Agentes` (`Id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 507
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`LotesPrecarga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`LotesPrecarga` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `FechaHora` DATETIME(6) NOT NULL,
  `CantidadInfracciones` INT NOT NULL,
  `NroLote` INT NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 585
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`LotesRenombrado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`LotesRenombrado` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `FechaHora` DATETIME(6) NOT NULL,
  `CantidadInfracciones` INT NOT NULL,
  `RenombradorAsignadoId` BIGINT NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_LotesRenombrado_RenombradorAsignadoId` (`RenombradorAsignadoId` ASC) VISIBLE,
  CONSTRAINT `FK_LotesRenombrado_AspNetUsers_RenombradorAsignadoId`
    FOREIGN KEY (`RenombradorAsignadoId`)
    REFERENCES `fluxsys_db_dev`.`AspNetUsers` (`Id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 113
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`TitularesVehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`TitularesVehiculo` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `PatenteVehiculo` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `MarcaVehiculo` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ModeloVehiculo` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TipoVehiculo` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `FechaTransferenciaVehiculo` DATETIME(6) NOT NULL,
  `NombreCompletoTitular` VARCHAR(500) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CuilTitular` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `DireccionCompletaTitular` VARCHAR(500) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CodigoPostalTitular` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `LocalidadTitular` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ProvinciaTitular` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `DocumentoTitular` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TipoDocumentoTitular` INT NOT NULL,
  `TipoDocumentoTitularOriginal` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `DepartamentoTitular` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CalleTitular` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `NroTitular` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `PisoTitular` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `DeptoTitular` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TipoTitular` SMALLINT NOT NULL,
  `Nombre` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Apellido` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `LocalidadTitularOriginal` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ProvinciaTitularOriginal` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 168575
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`Infracciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`Infracciones` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `TitularId` INT NULL DEFAULT NULL,
  `Lugar` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `FechaHora` DATETIME(6) NULL DEFAULT NULL,
  `Estado` INT NOT NULL,
  `Patente` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TipoVehiculoSacit` INT NOT NULL,
  `Extranjero` TINYINT(1) NOT NULL,
  `EquipoId` INT NULL DEFAULT NULL,
  `EquipoMedicionId` INT NULL DEFAULT NULL,
  `ValorMedido` FLOAT NOT NULL,
  `ValorMaximoPermitido` FLOAT NOT NULL,
  `UnidadMedida` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CodigoInfraccionId` INT NULL DEFAULT NULL,
  `ArticuloCodigo` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `IncisoCodigo` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `DescripcionCodigo` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `AbreviaturaCodigo` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `PuntosRestadosCodigo` INT NULL DEFAULT NULL,
  `ObservacionesCodigo` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ImagenPatenteId` INT NULL DEFAULT NULL,
  `ImagenDestacadaIndice` INT NOT NULL,
  `EstadoPago` INT NOT NULL,
  `FechaVencimiento` DATETIME(6) NOT NULL,
  `Fecha2doVencimiento` DATETIME(6) NOT NULL,
  `ValorUF` FLOAT NOT NULL,
  `PorcentajeDescuentoPagoVoluntario` FLOAT NOT NULL,
  `ValorMaxInfraccionUF` FLOAT NOT NULL,
  `GastosAdministrativos` FLOAT NOT NULL,
  `CotizacionUF` FLOAT NOT NULL,
  `DiasPagoVoluntario` INT NOT NULL,
  `Dias2doVencimiento` INT NOT NULL,
  `DiasDescargo` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `SolicitudPagoEPagos` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `SolicitudPagoHPagos` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ReferenciaPago` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `LotePrecargaId` INT NULL DEFAULT NULL,
  `LoteExportacionId` INT NULL DEFAULT NULL,
  `LoteConsultaId` INT NULL DEFAULT NULL,
  `LoteRenombradoId` INT NULL DEFAULT NULL,
  `LoteImpresionId` INT NULL DEFAULT NULL,
  `CodigoNegocioExportacionBA` VARCHAR(120) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `VerificadorId` BIGINT NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  `ImpresionExcluida` TINYINT(1) NOT NULL DEFAULT '0',
  `EtiquetasImagenes` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `FechaActaGenerada` DATETIME(6) NULL DEFAULT NULL,
  `FechaConsultada` DATETIME(6) NULL DEFAULT NULL,
  `FechaConsultando` DATETIME(6) NULL DEFAULT NULL,
  `FechaDescarte` DATETIME(6) NULL DEFAULT NULL,
  `FechaExportacion` DATETIME(6) NULL DEFAULT NULL,
  `FechaImpresionGenerada` DATETIME(6) NULL DEFAULT NULL,
  `FechaRenombrado` DATETIME(6) NULL DEFAULT NULL,
  `FechaVerificacion` DATETIME(6) NULL DEFAULT NULL,
  `TipoCirculacion` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `NoDistinguible` TINYINT(1) NOT NULL DEFAULT '0',
  `DescargoId` INT NULL DEFAULT NULL,
  `EstadoJuzgamiento` INT NOT NULL DEFAULT '0',
  `CredencialesPagoHeliPagos` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CredencialesPagoEPagos` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `AreasDeteccionImagenes` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `EstadoLuces` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TipoDeteccionString` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TipoDetecion` INT NOT NULL DEFAULT '0',
  `CuilTitular` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Infracciones_CodigoInfraccionId` (`CodigoInfraccionId` ASC) VISIBLE,
  INDEX `IX_Infracciones_EquipoId` (`EquipoId` ASC) VISIBLE,
  INDEX `IX_Infracciones_EquipoMedicionId` (`EquipoMedicionId` ASC) VISIBLE,
  INDEX `IX_Infracciones_ImagenPatenteId` (`ImagenPatenteId` ASC) VISIBLE,
  INDEX `IX_Infracciones_LoteConsultaId` (`LoteConsultaId` ASC) VISIBLE,
  INDEX `IX_Infracciones_LoteExportacionId` (`LoteExportacionId` ASC) VISIBLE,
  INDEX `IX_Infracciones_LoteImpresionId` (`LoteImpresionId` ASC) VISIBLE,
  INDEX `IX_Infracciones_LotePrecargaId` (`LotePrecargaId` ASC) VISIBLE,
  INDEX `IX_Infracciones_LoteRenombradoId` (`LoteRenombradoId` ASC) VISIBLE,
  INDEX `IX_Infracciones_TitularId` (`TitularId` ASC) VISIBLE,
  INDEX `IX_Infracciones_VerificadorId` (`VerificadorId` ASC) VISIBLE,
  INDEX `IX_Infracciones_DescargoId` (`DescargoId` ASC) VISIBLE,
  CONSTRAINT `FK_Infracciones_AspNetUsers_VerificadorId`
    FOREIGN KEY (`VerificadorId`)
    REFERENCES `fluxsys_db_dev`.`AspNetUsers` (`Id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_Infracciones_CodigosInfraccion_CodigoInfraccionId`
    FOREIGN KEY (`CodigoInfraccionId`)
    REFERENCES `fluxsys_db_dev`.`CodigosInfraccion` (`Id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_Infracciones_Descargos_DescargoId`
    FOREIGN KEY (`DescargoId`)
    REFERENCES `fluxsys_db_dev`.`Descargos` (`Id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_Infracciones_Equipos_EquipoId`
    FOREIGN KEY (`EquipoId`)
    REFERENCES `fluxsys_db_dev`.`Equipos` (`Id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_Infracciones_Equipos_EquipoMedicionId`
    FOREIGN KEY (`EquipoMedicionId`)
    REFERENCES `fluxsys_db_dev`.`Equipos` (`Id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_Infracciones_Imagenes_ImagenPatenteId`
    FOREIGN KEY (`ImagenPatenteId`)
    REFERENCES `fluxsys_db_dev`.`Imagenes` (`Id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_Infracciones_LotesConsulta_LoteConsultaId`
    FOREIGN KEY (`LoteConsultaId`)
    REFERENCES `fluxsys_db_dev`.`LotesConsulta` (`Id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_Infracciones_LotesExportacion_LoteExportacionId`
    FOREIGN KEY (`LoteExportacionId`)
    REFERENCES `fluxsys_db_dev`.`LotesExportacion` (`Id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_Infracciones_LotesImpresion_LoteImpresionId`
    FOREIGN KEY (`LoteImpresionId`)
    REFERENCES `fluxsys_db_dev`.`LotesImpresion` (`Id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_Infracciones_LotesPrecarga_LotePrecargaId`
    FOREIGN KEY (`LotePrecargaId`)
    REFERENCES `fluxsys_db_dev`.`LotesPrecarga` (`Id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_Infracciones_LotesRenombrado_LoteRenombradoId`
    FOREIGN KEY (`LoteRenombradoId`)
    REFERENCES `fluxsys_db_dev`.`LotesRenombrado` (`Id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_Infracciones_TitularesVehiculo_TitularId`
    FOREIGN KEY (`TitularId`)
    REFERENCES `fluxsys_db_dev`.`TitularesVehiculo` (`Id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 1619
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`Imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`Imagenes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `InfraccionId` INT NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  `BaseUrl` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `PathUrl` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Name` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Extension` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `SizeBytes` BIGINT NOT NULL,
  `FullUrl` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Etiqueta` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Imagenes_InfraccionId` (`InfraccionId` ASC) VISIBLE,
  CONSTRAINT `FK_Imagenes_Infracciones_InfraccionId`
    FOREIGN KEY (`InfraccionId`)
    REFERENCES `fluxsys_db_dev`.`Infracciones` (`Id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 4846
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`OverlaysSvg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`OverlaysSvg` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Svg` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ImagenId` INT NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  `InfraccionId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_OverlaysSvg_ImagenId` (`ImagenId` ASC) VISIBLE,
  INDEX `IX_OverlaysSvg_InfraccionId` (`InfraccionId` ASC) VISIBLE,
  CONSTRAINT `FK_OverlaysSvg_Imagenes_ImagenId`
    FOREIGN KEY (`ImagenId`)
    REFERENCES `fluxsys_db_dev`.`Imagenes` (`Id`)
    ON DELETE RESTRICT,
  CONSTRAINT `FK_OverlaysSvg_Infracciones_InfraccionId`
    FOREIGN KEY (`InfraccionId`)
    REFERENCES `fluxsys_db_dev`.`Infracciones` (`Id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`ReemplazosDatoTitular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`ReemplazosDatoTitular` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Propiedad` INT NOT NULL,
  `ValorActual` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `ValorReemplazo` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 184
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`Videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`Videos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `InfraccionId` INT NULL DEFAULT NULL,
  `CreatedAt` DATETIME(6) NULL DEFAULT NULL,
  `UpdatedAt` DATETIME(6) NULL DEFAULT NULL,
  `DeletedAt` DATETIME(6) NULL DEFAULT NULL,
  `IsDeleted` TINYINT(1) NOT NULL,
  `BaseUrl` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `PathUrl` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Name` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Extension` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `SizeBytes` BIGINT NOT NULL,
  `FullUrl` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `IX_Videos_InfraccionId` (`InfraccionId` ASC) VISIBLE,
  CONSTRAINT `FK_Videos_Infracciones_InfraccionId`
    FOREIGN KEY (`InfraccionId`)
    REFERENCES `fluxsys_db_dev`.`Infracciones` (`Id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `fluxsys_db_dev`.`__EFMigrationsHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fluxsys_db_dev`.`__EFMigrationsHistory` (
  `MigrationId` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ProductVersion` VARCHAR(32) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`MigrationId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
